string run_id
geometry_msgs/PoseStamped object_pose
geometry_msgs/PoseStamped pick_pose
geometry_msgs/PoseStamped place_pose
bool pick_only
---
bool success
uint16 error_code
string message
---
string stage
float32 progress
