uint8 PICK_LIFT_ONLY=1
uint8 FULL_PICK_PLACE=2
string run_id
string object_id
uint8 task_scope
geometry_msgs/PoseStamped object_pose
geometry_msgs/PoseStamped pick_pose
geometry_msgs/PoseStamped place_pose
string grasp_frame
---
bool pipeline_success
bool transport_prepare_attempted
pnp_interfaces/StageStatus stage_status
uint8 planning_replan_count
uint8 verify_pick_recheck_count
float32 planning_time_ms
uint16 error_code
string message
---
string inner_stage
float32 progress
