target_pose_publisher:
  ros__parameters:
    use_sim_time: true
    topic_name: /perception/target_pose
    publish_rate_hz: 2.0
    frame_id: world
    target_x: 0.16
    target_y: 0.0
    target_z: 0.12

target_pose_monitor:
  ros__parameters:
    use_sim_time: true
    topic_name: /perception/target_pose
